### ISSUE TITLE
default listen IP

### ISSUE THREAD

**Issue by iddq** [n7tae/mrefd#2]
pls change the default listen IPs to 0.0.0.0 and ::

**Comment by n7tae** [comment]
Sorry, but you're going to have to explain why this is important. To save 10 seconds with rconfig? It's certainly not appropriate for any system. In fact, most installations that are running so far don't support IPv6.

**Comment by iddq** [comment]
for user experience. it is not straightforward to everyone.

**Comment by mach327** [comment]
Specifically, if the user during ./rconfig overlooks setting an IP, `mrefd` does not complain even though it has no network capability. If it's then configured to interlink with another reflector, it will insist it is sending connection packets, but of course none can actually be sent. 

This makes for a debug session rather than a "Doh! I forgot to set a bind address!" and a recompile. 

A default ipv4 listen address would go a ways, or documentation of this particular mode to short-circuit the debug process, but best would be catching that lack of a properly configured IP and erroring at runtime with an illuminating message, plus adding a sanity check to rconfig to require at least one of i4 or i6.

**Comment by n7tae** [comment]
This will be fixed in the **next release**.

The rconfig script will refuse to write a configure.h file unless it has a valid reflector callsign and at least one IP address. The menu will contain comments that will suggest the values of 0.0.0.0 and/or ::. In addition, mrefd will terminate with a message and an EXIT_FAILURE unless its callsign and at least one IP passes a regular expression test.
