### ISSUE TITLE
Allow choosing a listening port

### ISSUE THREAD

**Issue by kc1awv** [n7tae/mrefd#7]
Allow the reflector owner to choose a listening port. This will enable running many reflectors on one server.

**Comment by n7tae** [comment]
This is a pretty big job to do properly. It will likely require a new script, radmin, that can administer the various instances as each instance will require its own systemd shells, unless each instance runs in a thread of a master control program. Either way, there is a lot of dev work.

Another problem is how to do interlinking between instances running on the same machine. Ideally this would be better handled by UNIX sockets instead of some UDP loop-back. Again there is some significant dev work here.

Also what about the mrefd.{interlink,blacklist,whitelist} files? Does each instance get its own files?

Since the port is only defined in configure.h, I'm thinking it's much easier to hack this issue than to formally support it.

Thoughts, anybody?

**Comment by kc1awv** [comment]
I will admit that this feature request is a bit self-serving and probably quite niche. I'm not saying that it shouldn't/couldn't be done, just that this issue came up when exploring some hosting options.

I have discovered a way to use containers as an interim solution at the moment, however.

**Comment by n7tae** [comment]
M17_PORT is configurable in the dht branch (to be merged in main).
